remote_theme: baagaard-usgs/just-the-docs
title: PyLith Installer
baseurl: /pylith-installer
#search_enabled: true
aux_links:
    "GitHub repository":
      - "//github.com/geodynamics/pylith_installer"

color_scheme: cig_lightbg
heading_anchors: false
search_enabled: true

title_image: images/cig_bluebg.png
software_version: 3.0.0-0
